spring:
  profiles:
      include:
      - aws
      - datasource
      - credentials
      - oauth2
      
# page 설정 
  data:
    web:
      pageable:
        one-indexed-parameters: true


# cors 설정
cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://look-outside.netlify.app/oauth/redirect
  