cloud:
  aws:
     credentials:
       access-key: AKIAY64IR3IZLEHCD64Z
       secret-key: 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
     s3:        
       bucket: elasticbeanstalk-us-west-1-616077318706
       dir: images
     region:
       static: us-west-1
       auto: false
     stack:
       auto: false
   
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR   