spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://look-outside.cz1vqpgfb5kt.us-west-1.rds.amazonaws.com:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
#    password: root
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 375740667528-vjhprd272fkvfs28vcq69hh2e2ga7njl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
      