spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://look-outside.cz1vqpgfb5kt.us-west-1.rds.amazonaws.com:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
#    password: root
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl