spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://look-outside.cz1vqpgfb5kt.us-west-1.rds.amazonaws.com:3306/lo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
#    password: root
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 375740667528-vjhprd272fkvfs28vcq69hh2e2ga7njl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          naver:
            clientId: 9_C0ruxN71m8RM9THt3w
            clientSecret: BnSdCIUL3C
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://springbootlookoutside-env.eba-khrbrhmx.us-west-1.elasticbeanstalk.com/login/oauth2/code/naver
            
            scope:
              - name
              - nickname
              - email
              - profile_image
            clientName: Naver
            
          kakao:
            clientId: 21e829ac4ace5d64c36a3251b2e4d21e
            clientSecret: JJzQF3heR0hySThDYVDya4hlBsJdtR83
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://springbootlookoutside-env.eba-khrbrhmx.us-west-1.elasticbeanstalk.com/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
          
        # Provider 설정
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

# cors 설정
cors:
  allowed-origins: '*'
  allowed-methods: '*'
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
  